using System;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace JuiceKing
{
    public enum ShopSection { Apples, Tickets, RemoveAds }

    /// <summary>One product card in the shop. Its texts are filled from <see cref="IapCatalog"/> by product id.</summary>
    [Serializable]
    public class ShopCard
    {
        public string productId;
        public RectTransform root;
        public Button button;
        public TextMeshProUGUI titleText;
        public TextMeshProUGUI amountText;
        public TextMeshProUGUI bonusText;
        public TextMeshProUGUI priceText;
        public GameObject badge;
        public Image badgeImage;
        public TextMeshProUGUI badgeText;
        [Tooltip("Glow and rays shown with the badge (featured packs).")]
        public GameObject[] highlights;
    }

    /// <summary>
    /// Premium shop: Golden Apple packs, Ad Ticket packs and Remove Ads in one scrolling popup, opened from the "+"
    /// buttons on the HUD. Cards are generated by the builder; everything they show comes from the catalog and the
    /// store (<see cref="Iap"/>), so prices and quantities are data-driven.
    /// </summary>
    public class ShopPopup : MonoBehaviour
    {
        public static ShopPopup I { get; private set; }

        public RectTransform window;
        public Image dim;
        public Button dimButton;
        public Button closeButton;
        public ScrollRect scroll;
        public RectTransform applesSection, ticketsSection, removeAdsSection;
        public ShopCard[] cards;

        [Header("Balances")]
        public TextMeshProUGUI applesBalance;
        public TextMeshProUGUI ticketsBalance;
        public RectTransform applesBalancePanel, ticketsBalancePanel;

        [Header("Feedback")]
        public TextMeshProUGUI statusText;
        [Tooltip("\"+85 GOLDEN APPLES\" that pops over the bought card.")]
        public TextMeshProUGUI gainText;
        public Button restoreButton;
        public Sprite popularRibbon, bestValueRibbon;

        bool _open;
        float _dimAlpha;
        // The first layout pass after opening can move the list: the section scroll is applied again a frame later.
        int _scrollFrames;
        ShopSection _scrollSection;
        int _statusSerial;
        float _storeCheckT;
        bool _wasReady;

        public bool IsOpen => _open;

        void Awake()
        {
            I = this;
            _dimAlpha = dim != null ? dim.color.a : 0.6f;
            foreach (var c in cards)
            {
                var card = c;
                card.button.onClick.AddListener(() => OnBuy(card));
            }
            if (closeButton != null) closeButton.onClick.AddListener(() => Close());
            if (dimButton != null) dimButton.onClick.AddListener(() => Close());
            if (restoreButton != null) restoreButton.onClick.AddListener(OnRestore);
            var gm = GameManager.I;
            if (gm != null)
            {
                gm.ApplesChanged += OnApples;
                gm.TicketsChanged += OnTickets;
            }
            if (gainText != null) gainText.gameObject.SetActive(false);
            Iap.Purchased += OnPurchased;
            Iap.Deferred += OnDeferred;
            gameObject.SetActive(false);
        }

        void OnDestroy()
        {
            Iap.Purchased -= OnPurchased;
            Iap.Deferred -= OnDeferred;
            if (GameManager.I != null)
            {
                GameManager.I.ApplesChanged -= OnApples;
                GameManager.I.TicketsChanged -= OnTickets;
            }
            if (_open)
            {
                Platform.Resume("shop");
                InputJoystick.Block("shop", false);
            }
        }

        public void Open(ShopSection section = ShopSection.Apples)
        {
            if (_open) return;
            _open = true;
            if (Iap.Provider != null && !Iap.IsReady) Iap.Provider.Reconnect();
            _wasReady = Iap.IsReady;
            Refresh();
            SetStatus(StoreStatus(), true);
            Platform.Pause("shop");
            InputJoystick.Block("shop", true);
            gameObject.SetActive(true);
            Tweener.Scale(window, Vector3.one * 0.55f, Vector3.one, 0.38f, Ease.OutBack);
            if (dim != null)
            {
                var c = dim.color;
                Tweener.Value(dim.transform, 0.2f, t => dim.color = new Color(c.r, c.g, c.b, _dimAlpha * t));
            }
            ScrollTo(section, true);
            _scrollSection = section;
            _scrollFrames = 2;
            Sfx.Play(SfxId.Whoosh, 0.3f, 1.2f);
        }

        /// <summary>What the status line says about the store itself (empty when it is ready).</summary>
        static string StoreStatus() =>
            Iap.IsReady ? "" : Iap.IsInitializing ? "Connecting to the store..." : "Store not available right now. Check your connection.";

        void LateUpdate()
        {
            if (_scrollFrames > 0 && --_scrollFrames == 0) ScrollTo(_scrollSection, true);
            if (!_open) return;
            // The store may finish connecting while the shop is open: prices and buttons come alive then.
            _storeCheckT -= Time.unscaledDeltaTime;
            if (_storeCheckT > 0f) return;
            _storeCheckT = 0.5f;
            bool ready = Iap.IsReady;
            if (ready != _wasReady)
            {
                _wasReady = ready;
                Refresh();
                SetStatus(StoreStatus(), true);
            }
        }

        public void Close()
        {
            if (!_open) return;
            _open = false;
            Platform.Resume("shop");
            InputJoystick.Block("shop", false);
            Sfx.Play(SfxId.Click, 0.5f);
            Tweener.Scale(window, window.localScale, Vector3.one * 0.6f, 0.16f, Ease.InQuad, () =>
            {
                if (!_open) gameObject.SetActive(false);
                window.localScale = Vector3.one;
            });
        }

        /// <summary>Scrolls so the section header sits at the top of the list (or as far as the list allows).</summary>
        public void ScrollTo(ShopSection section, bool instant = false)
        {
            var target = section == ShopSection.Tickets ? ticketsSection : section == ShopSection.RemoveAds ? removeAdsSection : applesSection;
            if (scroll == null || target == null) return;
            Canvas.ForceUpdateCanvases();
            float range = scroll.content.rect.height - scroll.viewport.rect.height;
            float to = range <= 0f ? 1f : 1f - Mathf.Clamp01(-target.anchoredPosition.y / range);
            scroll.StopMovement();
            if (instant)
            {
                scroll.verticalNormalizedPosition = to;
                return;
            }
            float from = scroll.verticalNormalizedPosition;
            Tweener.Value(scroll.transform, 0.45f, t => scroll.verticalNormalizedPosition = Mathf.Lerp(from, to, Ease.OutQuad(t)));
        }

        void Refresh()
        {
            bool busy = Iap.Busy;
            foreach (var card in cards)
            {
                var p = IapCatalog.Get(card.productId);
                card.root.gameObject.SetActive(p != null);
                if (p == null) continue;
                bool owned = Iap.Owns(p);
                bool available = Iap.IsAvailable(p);
                // VIP already claims every reward for free: Ad Tickets would be useless, so they are not sold to VIPs.
                bool vipCovers = p.kind == IapKind.Tickets && Ads.Vip;
                if (card.titleText != null) card.titleText.text = p.title;
                if (card.amountText != null) card.amountText.text = p.kind == IapKind.RemoveAds ? "" : "x" + p.amount.ToString("N0");
                if (card.bonusText != null)
                {
                    card.bonusText.gameObject.SetActive(p.bonusPercent > 0);
                    card.bonusText.text = "+" + p.bonusPercent + "% BONUS";
                }
                // Prices always come from the store (localized); "..." while it is still connecting.
                card.priceText.text = owned ? "OWNED" : vipCovers ? "VIP" : available ? Iap.PriceText(p) : Iap.IsInitializing ? "..." : "N/A";
                card.button.interactable = !owned && !vipCovers && !busy && available;
                bool featured = p.badge != IapBadge.None && !owned;
                if (card.highlights != null)
                    foreach (var h in card.highlights)
                        if (h != null) h.SetActive(featured);
                if (card.badge != null)
                {
                    card.badge.SetActive(featured);
                    if (card.badgeText != null) card.badgeText.text = p.badge == IapBadge.BestValue ? "BEST VALUE" : "POPULAR";
                    if (card.badgeImage != null)
                    {
                        var s = p.badge == IapBadge.BestValue ? bestValueRibbon : popularRibbon;
                        if (s != null) card.badgeImage.sprite = s;
                    }
                }
            }
            if (GameManager.I != null)
            {
                SetBalance(applesBalance, GameManager.I.Apples);
                SetBalance(ticketsBalance, GameManager.I.Tickets);
            }
        }

        static void SetBalance(TextMeshProUGUI t, int v)
        {
            if (t != null) t.text = v.ToString("N0");
        }

        void OnApples(int value, int delta)
        {
            if (!_open) return;
            SetBalance(applesBalance, value);
            if (applesBalancePanel != null) Tweener.Punch(applesBalancePanel, 0.2f, 0.3f, Vector3.one);
        }

        void OnTickets(int value, int delta)
        {
            if (!_open) return;
            SetBalance(ticketsBalance, value);
            if (ticketsBalancePanel != null) Tweener.Punch(ticketsBalancePanel, 0.2f, 0.3f, Vector3.one);
        }

        void OnBuy(ShopCard card)
        {
            if (!_open || Iap.Busy) return;
            var p = IapCatalog.Get(card.productId);
            if (p == null || Iap.Owns(p) || (p.kind == IapKind.Tickets && Ads.Vip)) return;
            if (!Iap.IsReady)
            {
                Sfx.Play(SfxId.Error, 0.35f);
                Tweener.Punch(card.button.transform, 0.12f, 0.25f, Vector3.one);
                SetStatus("Store not available right now.");
                return;
            }

            Sfx.Play(SfxId.Click, 0.5f);
            Haptics.Play(HapticKind.Selection);
            card.priceText.text = "...";
            foreach (var c in cards) c.button.interactable = false;
            SetStatus("Opening the store...", true);
            Iap.Purchase(p.id, result =>
            {
                if (this == null) return;
                Refresh();
                switch (result)
                {
                    case IapResult.Success:
                        // Celebrated by OnPurchased (it also covers restores and late deliveries).
                        break;
                    case IapResult.AlreadyOwned:
                        SetStatus(p.kind == IapKind.RemoveAds ? "You are already a VIP." : "This purchase was already delivered.");
                        break;
                    case IapResult.Cancelled:
                        SetStatus("Purchase cancelled.");
                        break;
                    case IapResult.Deferred:
                        SetStatus("Waiting for approval. Your items arrive as soon as it is approved.");
                        break;
                    case IapResult.Busy:
                        SetStatus("Another purchase is still in progress.");
                        break;
                    case IapResult.Unavailable:
                        Sfx.Play(SfxId.Error, 0.35f);
                        SetStatus("This item is not available right now.");
                        break;
                    default:
                        Sfx.Play(SfxId.Error, 0.35f);
                        Haptics.Play(HapticKind.Failure);
                        SetStatus("Purchase failed. Please try again.");
                        break;
                }
            });
        }

        /// <summary>Any grant (shop purchase, restore, a purchase finished after a restart): celebrate on its card.</summary>
        void OnPurchased(IapProduct p)
        {
            if (!_open) return;
            Refresh();
            foreach (var c in cards)
                if (c.productId == p.id)
                {
                    Celebrate(c, p);
                    return;
                }
        }

        void OnDeferred(IapProduct p)
        {
            if (_open) SetStatus("Waiting for approval. Your items arrive as soon as it is approved.");
        }

        void Celebrate(ShopCard card, IapProduct p)
        {
            Sfx.Play(SfxId.Reward, 0.6f);
            Sfx.Play(SfxId.Sparkle, 0.4f);
            Tweener.Punch(card.root, 0.12f, 0.35f, Vector3.one);
            SetStatus(p.kind == IapKind.RemoveAds ? "VIP active: every reward is now instant. Thank you!" : "Thank you for your purchase!");
            if (gainText == null) return;
            gainText.text = p.kind == IapKind.Apples ? "+" + p.amount.ToString("N0") + " GOLDEN APPLES"
                : p.kind == IapKind.Tickets ? "+" + p.amount.ToString("N0") + " AD TICKETS"
                : "VIP ACTIVE!";
            var rt = gainText.rectTransform;
            rt.position = card.root.position;
            Vector2 start = rt.anchoredPosition;
            gainText.gameObject.SetActive(true);
            gainText.alpha = 1f;
            Tweener.Value(rt, 1.3f, t =>
            {
                rt.anchoredPosition = start + new Vector2(0f, 160f * Ease.OutQuad(t));
                rt.localScale = Vector3.one * (t < 0.2f ? Ease.OutBack(t / 0.2f) : 1f);
                gainText.alpha = t < 0.7f ? 1f : 1f - (t - 0.7f) / 0.3f;
            }, () => gainText.gameObject.SetActive(false));
        }

        void OnRestore()
        {
            if (Iap.Busy) return;
            Sfx.Play(SfxId.Click, 0.5f);
            SetStatus("Restoring purchases...", true);
            bool hadNoAds = GameManager.I != null && GameManager.I.NoAds;
            Iap.Restore(ok =>
            {
                if (this == null) return;
                Refresh();
                bool gotNoAds = GameManager.I != null && GameManager.I.NoAds && !hadNoAds;
                SetStatus(!ok ? "Could not restore purchases. Check your connection." : gotNoAds ? "VIP restored!" : "Purchases restored. Nothing new to restore.");
            });
        }

        void SetStatus(string msg, bool sticky = false)
        {
            if (statusText == null) return;
            statusText.text = msg;
            statusText.gameObject.SetActive(!string.IsNullOrEmpty(msg));
            int serial = ++_statusSerial;
            if (!string.IsNullOrEmpty(msg) && !sticky)
                Tweener.Delay(3.5f, () =>
                {
                    if (this != null && serial == _statusSerial && statusText != null) statusText.gameObject.SetActive(false);
                });
        }
    }
}
